platform :ios, '13.0'

target 'DemoApp' do
  use_frameworks!

pod 'GapoSDK', :path => '../../GapoSDK'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_APP_SANDBOX'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5'
    end
  end
end

end
